# Generated by Django 4.1.1 on 2023-07-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
